import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const isProd = (process.argv[2] === "production");

// Get the path from the .env file for transferring ready files to the Obsidian plugin folder
let obsidianPath = "";
if (fs.existsSync(".env")) {
    const env = fs.readFileSync(".env", "utf-8");
    const match = env.match(/^OBSIDIAN_PLUGIN_PATH=(.+)$/m);
    if (match)
        obsidianPath = match[1];
}

// Plugin for automatic transfer of ready files to Obsidian after each build
const obsidianCopyPlugin = {
    name: 'obsidian-copy',
    setup(build) {
        build.onEnd(async () => {

            if (!obsidianPath) {
                console.log("[esbuild] Local copy path is not set in .env, skipping.");
                return;
            }

            try {
                if (!fs.existsSync(obsidianPath))
                    fs.mkdirSync(obsidianPath, { recursive: true });

                fs.copyFileSync("dist/main.js", path.join(obsidianPath, "main.js"));
                fs.copyFileSync("manifest.json", path.join(obsidianPath, "manifest.json"));

                console.log("[esbuild] Files successfully copied to Obsidian.");
            } catch (err) {
                console.error("Error when copying files to Obsidian:", err);
            }
        });
    }
};


const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/state",
        "@codemirror/view",
        "@codemirror/language",
        ...builtins],
    format: "cjs",
    target: "es2022",
    logLevel: "info",
    sourcemap: isProd ? false : "inline",
    minify: isProd,
    outfile: "dist/main.js",
    plugins: [obsidianCopyPlugin] // Enable the Copying plugin
});

if (isProd) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
